ca_perso_homepage:
    path:     /
    defaults: { _controller: CAPersoBundle:Perso:index }

ca_perso_view:
    path:     /{id}
    defaults: { _controller: CAPersoBundle:Perso:view }
    requirements:
      id: \d

ca_perso_edit:
    path:     /edit/{id}
    defaults: { _controller: CAPersoBundle:Perso:edit }
    requirements:
      id: \d

ca_perso_add_friend:
    path:     /add_remove_friend/{id}
    defaults: { _controller: CAPersoBundle:Perso:addRemoveFriend }
    requirements:
      id: \d

ca_perso_search:
    path:     /search
    defaults: { _controller: CAPersoBundle:Perso:search }

persos_list:
    path:     /persos
    defaults: { _controller: CAPersoBundle:Perso:list }

perso_list:
    path:     /perso/{id}
    defaults: { _controller: CAPersoBundle:Perso:show }
    requirements:
      id: \d