<?php

namespace CA\PersoBundle\Repository;

/**
 * FriendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends \Doctrine\ORM\EntityRepository
{
}
