<?php

namespace CA\PersoBundle\Repository;

/**
 * PersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoRepository extends \Doctrine\ORM\EntityRepository
{
}
